// Code generated by Slice Machine. DO NOT EDIT.

import Bio from './Bio/index.svelte';
import ContentIndex from './ContentIndex/index.svelte';
import Experience from './Experience/index.svelte';
import Hero from './Hero/index.svelte';
import ImageBlock from './ImageBlock/index.svelte';
import RichText from './RichText/index.svelte';
import SkilledList from './SkilledList/index.svelte';

export const components = {
	bio: Bio,
	content_index: ContentIndex,
	experience: Experience,
	hero: Hero,
	image_block: ImageBlock,
	rich_text: RichText,
	skilled_list: SkilledList
};
